---
- hosts: docker
  become: true

  tasks:
    - name: Install docker
      vars:
        docker_install_compose: true
        docker_users:
          - ubuntu
        pip_install_packages:
          - name: docker
          - name: docker-compose
      roles:
        - role: geerlingguy.pip
        - role: geerlingguy.docker
    - name: Install app
      remote_user: ubuntu
      roles:
        - role: '../roles/app_python'
