version: "3.8"
services:
  app_python:
    build: ../../../../app_python
    ports:
      - 8000:8000
    image: lissa00/devops:latest

    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"


